export {FlexContainer} from "./styles/FlexContainer"
export {Title} from "./styles/Title"
export {TextContainer} from "./styles/TextContainer"
export {TextError} from "./styles/TextError"
export {Image} from "./styles/Image"